version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-feed-viewer-app
    depends_on:
      - postgres
    environment:
      DB_HOST: stock-feed-viewer-postgres:5432
      STOCK_FEED_API_HOST: stock-feed-app:8080
    ports:
      - "8090:8090"
    networks:
      - stock-feed-viewer-network
      - stock-feed-network

  postgres:
    image: postgres:latest
    container_name: stock-feed-viewer-postgres
    environment:
      POSTGRES_DB: stock_feed_viewer_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - stock-feed-viewer-network

volumes:
  postgres_data:

networks:
  stock-feed-viewer-network:
  stock-feed-network:
    external: true
