server:
  port: 8090

spring:

  application:
    name: stocksfeedviewer

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_DATABASE:stock_feed_viewer_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  flyway:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_DATABASE:stock_feed_viewer_db}
    user: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

stock-feed-api:
  login: user
  password: password

displaying:
  delay: ${DISPLAY_DELAY:5000} # 5 * 1000ms = 5 sec

logging:
  level:
    org:
      springframework:
        security: DEBUG
        data:
          datasource: DEBUG